// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vukkhgyhmyzczholwhxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1a2toZ3lobXl6Y3pob2x3aHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzQyMDIsImV4cCI6MjA2MDkxMDIwMn0.zZ3V6rUvhXgDkc6kiWr5e7SeBpgSFiwX_Xqfqma5vZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);